src/Entity/Theme.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ThemeRepository")
 */
class Theme
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ImageFond;

    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ImageCapture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ColorFond;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $KeyWord;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $KeyRoot;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Comments;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageCapture(): ?string
    {
        return $this->ImageCapture;
    }

    public function setImageCapture(string $ImageCapture): self
    {
        $this->ImageCapture = $ImageCapture;

        return $this;
    }

    public function getImageFond(): ?string
    {
        return $this->ImageFond;
    }

    public function setImageFond(string $ImageFond): self
    {
        $this->ImageFond = $ImageFond;

        return $this;
    }

    public function getColorFond(): ?string
    {
        return $this->ColorFond;
    }

    public function setColorFond(string $ColorFond): self
    {
        $this->ColorFond = $ColorFond;

        return $this;
    }

    
    public function getKeyRoot(): ?string
    {
        return $this->KeyRoot;
    }

    public function setKeyRoot(string $KeyRoot): self
    {
        $this->KeyRoot = $KeyRoot;

        return $this;
    }


    public function getComments(): ?string
    {
        return $this->Comments;
    }

    public function setComments(string $Comments): self
    {
        $this->Comments = $Comments;

        return $this;
    }

    public function getKeyWord(): ?string
    {
        return $this->KeyWord;
    }

    public function setKeyWord(string $KeyWord): self
    {
        $this->KeyWord = $KeyWord;

        return $this;
    }

}

src/Controller/ProController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Post;
use App\Entity\Category;
use App\Entity\Article;
use App\Entity\Devis;
use App\Entity\Customer;
use App\Entity\Comments;
use App\Entity\Transaction;
use App\Entity\ReponsePostAds;
use App\Entity\Abonnement;
use App\Entity\DevisAccept;
use App\Entity\DevisFinish;
use App\Entity\DevisValid;
use App\Entity\DevisViewed;
use App\Entity\Images;
use App\Entity\Documment;
use App\Entity\Services;
use App\Entity\Labels;
use App\Entity\Videos;
use App\Entity\Offer;
use App\Entity\Conseil;
use App\Entity\Evaluations;
use App\Entity\GuidePrice;
use App\Entity\ChantierOfMouth;
use App\Entity\SiteInternet;
use App\Repository\OfferRepository;
use App\Repository\UserRepository;
use App\Repository\AbonnementRepository;
use App\Repository\ArticleRepository;
use App\Repository\ServicesRepository;
use App\Repository\CustomerRepository;
use App\Repository\DevisRepository;
use App\Repository\PostRepository;
use App\Repository\CategoryRepository;
use App\Repository\EvaluationsRepository; 
use App\Repository\CitiesRepository;
use App\Repository\EmojiRepository;
use App\Repository\VideosRepository;
use App\Repository\ThemeImageRepository;
use App\Repository\ThemeColorRepository;
use App\Repository\ThemeRepository;
use App\Repository\DevisAcceptRepository;
use App\Repository\DevisValidRepository;
use App\Repository\DevisFinishRepository;
use App\Repository\DevisViewedRepository;
use App\Repository\DocummentRepository;
use App\Repository\ImagesRepository;
use App\Repository\SiteInternetRepository;
use App\Repository\LabelsRepository;
use App\Repository\ConfigsiteRepository;
use FOS\UserBundle\Model\UserManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Translation\TranslatorInterface;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpClient\HttpClient;
use Dompdf\Dompdf;
use Dompdf\Options;

/**
* @Route("/pro")
*/
class ProController extends AbstractController
{
   
    /**
    * @Route("/dashbord", name="pro_dashbord")
    * @param $user to find pro owner infos
    */
    public function dashbord(Security $security, ThemeRepository $themeRep, ThemeColorRepository $themeColorRep, ThemeImageRepository $themeImageRep, ConfigsiteRepository $configsiteRep, DevisRepository $devisRep, PostRepository $postRep, ServicesRepository $serviceRep, DevisAcceptRepository $devisAcceptRep, DevisValidRepository $devisValidRep, DevisFinishRepository $devisFinishRep)
    {
        // The second parameter is used to specify on what object the role is tested.
        $this->denyAccessUnlessGranted('ROLE_USER_PROFESSIONAL', null, 'Vous n\'as pas de droit d\'accèder à cette page!');

        if( $security->getUser()->getIsVerified() !== true) {

            return  $this->redirectToRoute('email_comfirm');

        }

        $services = $serviceRep->findByUser($security->getUser());
        //dump($services);die;
        $array = Array();
        foreach ($services as $key => $value) {
        $array[] = $value->getCategoryId();
        }

        $categoryId =  $array;
        $arrayData1 = array( 1=>  ($categoryId), 
                            2=> $security->getUser()->getNumDepartement() . '%',
                            );

        $devis = $devisRep->findByZipCodeAndCity($arrayData1);
       //dump( $devis);die;
        $nbdevis = count($devis);

        $arrayData2 = array(1=>  ($categoryId), 
                            2=> $security->getUser()->getNumDepartement() . '%',
                            );
        $postsAdsArray = $postRep->filterByCategoryOrCityOrZipcodeOrDepartement($arrayData2);
        //dump($postsAdsArray);die;
        $postsAds = count( $postsAdsArray ) > 0 ? $postsAdsArray : [];
        $distances = array();
        if(count($postsAds) > 0) {

            //Get DISTANCE AND CALCULATE BY KM USING LAT AND LONG
            foreach ($postsAds as $key => $post) {

                $cityArray1['lat'] = $post->getCity()->getVilleLatitudeDeg();
                $cityArray1['lng'] = $post->getCity()->getVilleLongitudeDeg();
                $cityArray2['lat'] = $security->getUser()->getUserCity()->getVilleLatitudeDeg();
                $cityArray2['lng'] = $security->getUser()->getUserCity()->getVilleLongitudeDeg();
                $distance = $this->getDistance($cityArray1, $cityArray2);
                if ( $distance <= $security->getUser()->getKilometer()) {
                    $distances[$post->getId()] = $distance ;
                }

            }

        }
        //dump($distances);die;

        //Get config site
        $configsite = $configsiteRep->findOneByIsActive();
        //THEMES PAGES
        $thems =  $themeRep->findAllArray();
        $themeImages = $themeImageRep->findAllArray();
        $themeColors = $themeColorRep->findAllArray();
        $thems = count($thems) > 0 ? $thems : [];
        $themeImages = count($themeImages) > 0 ? $themeImages : [];
        $themeColors = count($themeColors) > 0 ? $themeColors : [];
        $them = array();
        $themes = array();
        $themesColor = array();

        if(count($thems) > 0) {
            foreach($thems as $key => $value) {
                $them[$value->getKeyWord()] = $value;
            }
        }
        //dump($them);die;

        if(count($themeImages) > 0) {
            foreach($themeImages as $key => $value) {
                $themes[$value->getThemeId()->getKeyWord()][$value->getKeyWord()] = $value;
            }
        }
        //dump($themes);die;

        if(count($themeColors) > 0) {
            foreach($themeColors as $key => $value) {
                $themesColor[$value->getThemeId()->getKeyWord()][$value->getKeyWord()] = $value;
            }
        }
        //dump($themesColor);die;

        return $this->render('pro/dashbord.html.twig', [
            'numberDevis' => $nbdevis,
            'distances'=> $distances,
            'postAds'=> $postsAds,
             'nbProjectDispo'=> count($postsAds),
             'user'=> $security->getUser(),
             'configsite'=> $configsite,
             'themesImage'=> $themes,
             'themesColor'=> $themesColor,
             'themes'=> $them,

        ]);
    }


    /**
    * @Route("/lists-projects-disponible", name="pro_dispos_projects")
    */
    public function dispoProjects(Request $request, ThemeRepository $themeRep, ThemeColorRepository $themeColorRep, ThemeImageRepository $themeImageRep, ConfigsiteRepository $configsiteRep, Security $security, CategoryRepository $catRep, PostRepository $postRep, ServicesRepository $serviceRep, DevisRepository $devisRep)
    {
        // The second parameter is used to specify on what object the role is tested.
        $this->denyAccessUnlessGranted('ROLE_USER_PROFESSIONAL', null, 'Vous n\'as pas de droit d\'accèder à cette page!');
        
        if( $security->getUser()->getIsVerified() !== true) {

            return  $this->redirectToRoute('email_comfirm');

        }
        
        //HERE GET PROJECT DISPO ESPECTED DIRECTLY BY PRO SPECIALITY or Zipcage or Departement
    
        $services = $serviceRep->findByUser($security->getUser());
        $array = Array();
        foreach ($services as $key => $value) {
           $array[] = $value->getCategoryId();
        }
        $categoryId =  $array;
        $arrayData = array(1=>  ($categoryId), 
                            2=> $security->getUser()->getNumDepartement() . '%',
                            );          
        $postsAdsArray = $postRep->filterByCategoryOrCityOrZipcodeOrDepartement($arrayData);
        $postsAds = count( $postsAdsArray ) > 0 ? $postsAdsArray : null;
        //dump($postsAds);die;

        if($postsAds !== null && !is_null($request->query->get('switch_periodity'))) {
            $arrayPostAds = Array();
            foreach ($postsAds as $key => $value) {

                $datetime1 = $value->getPostAdsDateCrea();
                $datetime2 = new \DateTime('now');
                $interval = $datetime1->diff($datetime2);

                    if ((int) $interval->format('%R%a') < (int) $request->query->get('switch_periodity')) {
                        $arrayPostAds[$key] = ['id'=> $value->getId(), 
                                                'title'=> $value->getCategoryId()->getCategTitle(),
                                                'firstname'=> $value->getPostUserId()->getFirstname(),
                                                'city'=> $value->getCity()->getVilleNomReel(),
                                                'description'=> $value->getPostAdsTravauxDescription(),
                                                'date'=> $value->getPostAdsDateCrea()
                                                ];
                    }
                    else {
                        $arrayPostAds[$key] = ['id'=> $value->getId(), 
                                                'title'=> $value->getCategoryId()->getCategTitle(),
                                                'firstname'=> $value->getPostUserId()->getFirstname(),

templates/pro/dashbord.html.twig
	{% extends  'base.html.twig' %}

	{% block stylesheets %}

	<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />-->
	<script src="https://cdn.linearicons.com/free/1.0.0/svgembedder.min.js"></script>
	<link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
	<!-- CSS Files -->
	<link href="{{ absolute_url('/assets/sweetalert2/dist/sweetalert2.min.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/assets/css/now-ui-kit.min.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/assets/css/bootstrap.min.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/animate/animate.min.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/assets/loadbar/css/loading-bar.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/assets/select2-develop/dist/css/select2.min.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/assets/swiper/dist/css/swiper.min.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/assets/form-multistep/form-step.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/css/loading.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/css/loading-btn.css') }}" rel="stylesheet" />
	<link href="{{ absolute_url('/css/style.css') }}" rel="stylesheet" />

	<style>
	/* Set the size of the div element that contains the map */
	#map, #map2 {
		height: 400px;  /* The height is 400 pixels */
		width: 100%;  /* The width is the width of the web page */
	}
		/** CSS THEMES
			warning dark : rgb(255, 144, 0)
			warning claire : #ffc107
			gray dark: rgb(119, 119, 119) ou #777
			gray claire : rgb(240, 240, 240) ou #bfbfbf
			white claire : rgb(248, 248, 248) ou #ffffff
			black claire: rgba(0, 0, 0, 95%)
			black dark : #000000

		**/
		.navbar, .bg-grey {
			background: {{ themesColor['HEADER']['HEADER_FONT_COUL_1'].Color != null ? themesColor['HEADER']['HEADER_FONT_COUL_1'].Color : 'rgb(240, 240, 240)' }} !important;
			color: {{ themesColor['HEADER']['HEADER_TEXT_COUL_1'].Color != null ? themesColor['HEADER']['HEADER_TEXT_COUL_1'].Color : 'rgb(248, 248, 248)' }} !important;
		}
		.navbar-mega, .sidepanel, .bg-darkgray {
			background: {{ themesColor['HEADER']['HEADER_FONT_COUL_2'].Color != null ? themesColor['HEADER']['HEADER_FONT_COUL_2'].Color : '#777'}} !important;
			color: {{ themesColor['HEADER']['HEADER_TEXT_COUL_2'].Color != null ? themesColor['HEADER']['HEADER_TEXT_COUL_1'].Color : 'rgb(248, 248, 248)' }} !important;
		}

		button, .bg-warning, .icon-sondage, .triangle {
			background: {{ themes['BUTTON_FOND_COLOR'].colorFond != null ? themes['BUTTON_FOND_COLOR'].colorFond : 'rgb(255, 144, 0)' }} !important;
			color: {{ themes['BUTTON_TEXT_COLOR'].colorFond != null ? themes['BUTTON_TEXT_COLOR'].colorFond : ' rgb(248, 248, 248)' }} !important;
		}
		.triangle::after {
			border-color: transparent transparent {{ themes['BUTTON_FOND_COLOR'].colorFond != null ? themes['BUTTON_FOND_COLOR'].colorFond : 'rgb(255, 144, 0)' }} {{ themes['BUTTON_FOND_COLOR'].colorFond != null ? themes['BUTTON_FOND_COLOR'].colorFond : 'rgb(255, 144, 0)' }} !important;
		}

		.man-young-container .text-title {
			color: {{ themesColor['TEXT_TITLE']['TEXT_TITLE_COLOR_3'].Color != null ? themesColor['TEXT_TITLE']['TEXT_TITLE_COLOR_3'].Color : ' #ffc107' }} !important;
		}
		.man-young-container .text-desc {
			color: {{ themesColor['TEXT_DESCRIPTION']['TEXT_DESCRIPTION_COLOR_1'].Color != null ? themesColor['TEXT_DESCRIPTION']['TEXT_DESCRIPTION_COLOR_1'].Color : ' rgb(248, 248, 248)' }} !important;
		}
		.text-dark {
			color: {{ themesColor['TEXT_TITLE']['TEXT_TITLE_COLOR_2'].Color != null ? themesColor['TEXT_TITLE']['TEXT_TITLE_COLOR_2'].Color : ' #ffc107' }} !important;
		}
		p, .text-secondary {
			color: {{ themesColor['TEXT_DESCRIPTION']['TEXT_DESCRIPTION_COLOR_2'].Color != null ? themesColor['TEXT_DESCRIPTION']['TEXT_DESCRIPTION_COLOR_2'].Color : ' rgb(248, 248, 248)' }} !important;
		}
		.text-warning {
			color: {{ themesColor['TEXT_TITLE']['TEXT_TITLE_COLOR_3'].Color != null ? themesColor['TEXT_TITLE']['TEXT_TITLE_COLOR_3'].Color : ' #ffc107' }} !important;
		}
		.text-white {
			color: {{ themesColor['TEXT_TITLE']['TEXT_TITLE_COLOR_1'].Color != null ? themesColor['TEXT_TITLE']['TEXT_TITLE_COLOR_1'].Color : ' #ffffff' }} !important;
		}
		.page-header-image {
			background-blend-mode: overlay !important;
			background-color: {{ themes['BUTTON_FOND_COLOR'].colorFond != null ? themes['BUTTON_FOND_COLOR'].colorFond : 'rgba(255, 144, 0, 50%)' }} !important;
		}
		.section-footer {
			background-image: url(/uploads/themes/{{ themes['FOOTER'].imageFond != null ? themes['FOOTER'].imageFond : 'footer_bg.jpg'}}) !important;
			background-color: {{ themes['FOOTER'].colorFond != null ? themes['FOOTER'].colorFond : 'rgba(19, 19, 19, 95%)'}}) !important;
			background-blend-mode: overlay !important;
		}
	</style>

	{% endblock %}

	{% block body %}

	<div class="page-header page-header-image-gallery page-headers-pros">
		<div class="page-header-image animated pulse" data-parallax="true" style="background-image: url('/uploads/themes/{{ themes['SPACE_PRO'].imageFond != null ? themes['SPACE_PRO'].imageFond :' slide-inscription.jpg' }}'); background-position: 0 50px !important;">
		</div>
		
		<!--Begin heder-menu pro space -->
		{% include "./pro/menu/header-menu.html.twig" %}
		<!-- End header-menu pro space -->

		<!-- Begin for row content header parallax -->
		<div class="row d-flex justify-content-center font-weight-light">
			<!-- ############# Begin slide beside -->
			<div class="col-12 col-md-8" style="padding-top: 1em;">
				<div class="container border-0">
					<div class="w-100 d-flex flex-column pb-4 justify-content-center">
						<div class="h4 text-white text-uppercase">
							Bienvenu dans l'espace professionel
						</div>
					</div>
				</div>
			</div>
			<!-- ############# End slide beside -->
		</div>
	</div>
	<!--END HEADER-->


	<div class="jumbotron bg-transparent">
		<main class="section-1 section-main bg-white">
			<!--Begin section  of the list ads by artisan-->
			<section class="bg-transparent">
				<div class="container">
					<div Class="row">
					
						<!-- Begin menu top pro -->
						{% include "./pro/menu/top-menu.html.twig" %}
						<!-- End menu top pro -->

						<!-- Begin menu left pro -->
						{% include "./pro/menu/left-menu.html.twig" %}
						<!-- End menu left pro-->

						<div class="col-12 col-sm-8 pt-4">
							<div class="container-content-pro-space-right">
								<div class="card text-center">
									<div class="card-header p-2 font-weight-bold bg-darkgray">
										<h5>{{ nbProjectDispo }} PROJETS DISPONIBLES SUR MON SECTEUR</h5>
									</div>
									<div class="card-body">
										
										<ul class="list-group list-group-flush text-secondary">
										{% if postAds|length > 0 %}
										    {% for post in postAds %}
												<li class="list-group-item">
													<div class="d-block">
														<div class="d-flex flex-row align-items-center justify-content-around">
															<div class="">
																<div class="rounded-circle d-block" style="width: 80px; height: 80px; background: orange;">
																	<span class="lnr lnr-clock" style="font-size: 64px; line-height: 80px;"></span>
																</div>
															</div>
															<div class="px-2 info-ads-detail">
																<a href="{{ path('pro_one_detail_ads_projects', {id: post.id}) }}" class="text-reset"><h3 class="d-block text-left"> {{ post.getCategoryId().getCategTitle() }} ( {{ post.getTypeId().getTitle() }} ) </h3></a>
																<p class="d-block text-dark text-left">
																	{{ post.getPostUserId().getFirstname() }} - à {{ post.getCity().getVilleNomReel() }} 
																	{% for key, distance in distances %}
																		{% if key == post.getId() %}
																		(Aviron à {{ distance }} km)
																		{% endif %}
																	{% endfor %} <br>
																	<span class="text-secondary">{{ post.getPostAdsTravauxDescription() }}</span>
																</p>
															</div>
														</div>
													</div>
													<div class="d-block text-center float-left">{{ post.getPostAdsDateCrea | date('d/m/y H:i:s') }}</div>
												</li>
											{% endfor %}
                                        {% else %}
											<li class="list-group-item">AUCUN RESULTAT</li>
										{% endif %}
										</ul>
										
									</div>
								    <div class="card-footer text-muted pb-4">
									 <a href="{{ path('pro_dispos_projects') }}" class="btn-outline-warning text-warning">Voir tous les projets disponibles</a>
								    </div>
								</div>

								<div class="card">
									<div class="card-header bg-darkgray p-1 text-white text-uppercase"> <h6 class="card-title"><span class="lnr lnr-map-marker" style="font-size: 32px;"></span></span> &nbsp; Ma zone de prescription</h6></div>
									<div class="card-body">
										<div class="row">
											<div class="col-12 h-100">
												<div id="map">
												{# <div id="pano"></div> #}
												</div>
												<div class="d-block text-uppercase text-center pt-2">
													<a href="{{ path('pro_geolocation_map_edit') }}" class="btn btn-warning text-decoration-none">Modifier ma zone géographique</a>
												</div>
											</div>
										</div>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</section>
			<!--End section  of the list ads by artisan-->
	
			<!--Begin section the Presse Talk US -->
			<section id="" class="bg-transparent">
			<div class="container  bg-white">
				<div class="row d-flex justify-content-center py-4">
					<div class="col-12 text-center">
						<h5 class="text-uppercase">Restez connecté</h5>
						<div class="text-secondary small"><p class=" subtitle ">
							Pour être certain de ne rater aucun chantier, téléchargez l’application mobile pour suivre les projets lorsque vous êtes en déplacement.
						</div>
					</div>
					<div class="col-12 col-sm-6 lg-8 text-center">
						<img class="" src="{{ absolute_url('/assets/img/photos/app-mobile.png') }}"></img>
					</div>
					<div class="col-12 col-sm-6 lg-4 d-flex flex-column justify-content-center text-secondary">
						<a class="btn btn-outline-secondary d-flex flex-row text-center align-items-center">
							<span class="pro-icon mb-3">
								<span class="icon-message-pro">
									<object type="image/svg+xml" data="{{ absolute_url('/assets/icon/apple_icon-icons.com_62745.svg') }}" class="icon-message-pro icon-bike">
										apple
									</object>
								</span>
							</span>
							<span class="">
								<span class="text-center ">Disponible sur <span/><br>
								<span class="font-weight-capitalize">App Store<span/>
							<span/>
						</a>
						<a class="btn btn-outline-secondary d-flex flex-row align-items-center">
							<span class="pro-icon mb-3">
								<span class="icon-message-pro">
									<object type="image/svg+xml" data="{{ absolute_url('/assets/icon/Google_Play_icon-icons.com_66988.svg') }} " class="icon-message-pro icon-bike">
										play
									</object>
								</span>
							</span>
							<span class="text-center ">
								<span class="">Disponible sur <span/><br>
								<span class="font-weight-capitalize">Google Play<span/>
							<span/>
						</a>
					</div>
				</div>
			</div>
			</section>
			<!--End section the Presse Talk US  -->

		</main>

		{% include "./pro/footer/footer.html.twig" %}

	</div>

	{% endblock %}

	{% block javascripts %}

	<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	 <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>-->
	  <!-- MESSAGE NTIFICATION -->
	<script src="{{ absolute_url('/assets/sweetalert2/dist/sweetalert2.all.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/sweetalert2/dist/sweetalert2.min.js') }}"></script>
	<!--Local-->
	<script src="{{ absolute_url('/assets/loadbar/js/loading-bar.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/core/jquery.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/core/bootstrap.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/now-ui-kit.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/core/popper.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/plugins/bootstrap-switch.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/plugins/nouislider.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/swiper/dist/js/swiper.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/select2-develop/dist/js/select2.full.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/select2-develop/dist/js/select2.min.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/app.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/map.js') }}"></script>
	<script src="{{ absolute_url('/assets/js/pro.js') }}"></script>
	<script src="{{ absolute_url('/assets/form-multistep/form-step.js') }}"></script>

	{% endblock %}